### ISSUE TITLE
What are prerequisites to run this dll in newly installed os pc in win 7,8,10

### ISSUE THREAD

**Issue by VishmayShah** [0x1mason/GribApi.NET#19]
What are prerequisites to run this dll in newly installed os pc in win 7,8,10
like c++ packs and compilers, framewords

so that it can run without visual studio
actually i have uninstalled vs and now i am getting error that cannot load dll

**Comment by 0x1mason** [comment]
Try this: ~~https://www.microsoft.com/en-us/download/details.aspx?id=30679~~
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by 0x1mason** [comment]
If that doesn't work, try .NET 4. Let me know what did the trick.

**Comment by VishmayShah** [comment]
still Not working , i have win 10  os 
The type initializer for 'Grib.Api.GribFile' threw an exception.

Exception : System.Exception: Can't load DLL C:\Program Files (x86)\MareCast\FMIDataSetup\Grib.Api\lib\win\x86\Grib.Api.Native.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found

   --- End of inner exception stack trace ---

   at Grib.Api.Interop.Util.Win32.LoadWin32Library(String libPath)

   at Grib.Api.GribEnvironmentLoadHelper.BootStrapLibrary()

   at Grib.Api.GribEnvironment.Init()

   at Grib.Api.GribFile..cctor()

StackTrace :    at Grib.Api.GribFile..ctor(String fileName)

   at FMIDataRetrive.FMIDataRetrive.InsertWeatherPropertyData(String readPath, Int32 propertyID, Int32 regionID, Int32 timestep, Int32 subRegionID, Double latitude1, Double longitude1, Double latitude2, Double longitude2)

   at FMIDataRetrive.FMIDataRetrive.GetRegionWeatherDetails(Int32 weatherPropertyID, Int32 regionID, Int32 subRegionID, Double latitude1, Double longitude1, Double latitude2, Double longitude2, DataSet dsConfig)

**Comment by VishmayShah** [comment]
start working with unstalling/uninstalling many vc++ runtime version, dont know which version it is
