### ISSUE TITLE
System.AccessViolationException in Grib.Api.dll

### ISSUE THREAD

**Issue by jnyrup** [0x1mason/GribApi.NET#24]
Sometimes when I run GribApi.NET in VS15 I get a `System.AccessViolationException`.

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Grib.Api.Interop.SWIG.GribApiProxyPINVOKE.GribIteratorDelete(HandleRef jarg1)
   at Grib.Api.Interop.SWIG.GribApiProxy.GribIteratorDelete(GribValuesIterator i) in c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\Interop\SWIG\GribApiProxy.cs:line 353
   at Grib.Api.Interop.AutoRef.Finalize() in c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\Interop\AutoRef.cs:line 51
```

I noticed when inspecting `GribIteratorDelete(GribValuesIterator i)` that `i._disposed` is `true` before calling `GribApiProxyPINVOKE.GribIteratorDelete`.

Please let me know if you need more info.
Thank you in advance

**edit:**
I found the problematic code and a solution.

```
using (var file1 = new GribFile("path-to-file"))
using (var file2 = new GribFile("path-to-file"))
{
    var msg1 = file1.First();
    var msg3 = file2.First();

    var msgEnumerator1 = msg1.GetEnumerator();
    var msgEnumerator2 = msg2.GetEnumerator();

    while(msgEnumerator1.MoveNext() && msgEnumerator1.MoveNext()){
        // do something
    }
}
```

The solution was to encapsulate `msgEnumerator1` and `msgEnumerator2` in `using`

```
using (var file1 = new GribFile("path-to-file"))
using (var file2 = new GribFile("path-to-file"))
{
    var msg1 = file1.First();
    var msg3 = file2.First();

    using(var msgEnumerator1 = msg1.GetEnumerator())
    using(var msgEnumerator2 = msg2.GetEnumerator())
    {
        while(msgEnumerator1.MoveNext() && msgEnumerator1.MoveNext()){
            // do something
        }
    }
}
```

**Comment by 0x1mason** [comment]
I'm going to reopen this so I can see if there's a more elegant solution for users.

**Comment by 0x1mason** [comment]
Your first bit of code should work in the next release.
