### ISSUE TITLE
SQL Server CLR containing Grib.Api

### ISSUE THREAD

**Issue by bnasko** [0x1mason/GribApi.NET#88]
Hi,
I've been attempting to add Grib.Api (tried both latest beta and current production versions) to an SQL CLR. I keep getting this error:

System.DllNotFoundException: Unable to load DLL 'Grib.Api.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
System.DllNotFoundException: 
   at Grib.Api.Interop.Util.GribApiNative.CreateFileHandleProxy(String filename)
   at Grib.Api.GribFile..ctor(String fileName)
   at WeatherDbClr.UserDefinedFunctions.GetGfsFcstAnl2()

These are the things I have done so far without any success:

1. Added the following two commands to my function:
Environment.SetEnvironmentVariable("GRIB_API_DIR_ROOT", "C:\db", EnvironmentVariableTarget.Process)
GribEnvironment.Init()

2. Added the Grib.Api folder to the server at the specified path and ensured that SQL server has access to that folder.

3. Installed VC++ 2013, then 2015.

Thanks in advance!!

**Comment by IdahoSixString** [comment]
For Sql CLR you need to register the dll with Sql server.
________________________________

**Comment by bnasko** [comment]
Thanks for the reply! How would I go about registering it with SQL server? And which DLL exactly should I be registering?

I did add Grib.Api.dll as an assembly in the database.

**Comment by bnasko** [comment]
I also tried to add Grib.Api.Native.dll but got the following error:
Msg 6544, Level 16, State 1, Line 1
CREATE ASSEMBLY for assembly 'Grib.Api.Native' failed because assembly 'Grib.Api.Native' is malformed or not a pure .NET assembly. 
Unverifiable PE Header/native stub.

**Comment by IdahoSixString** [comment]
Makes sense since it is pinvoke c library.
________________________________

**Comment by bnasko** [comment]
Is there any workaround to get this to work as CLR?

**Comment by IdahoSixString** [comment]
@SqlUser12 Not that I am aware of. What is it you are trying to exactly accomplish?

**Comment by bnasko** [comment]
I have a short script that pulls only 1 variable from NOAA's GFS grib. I wanted to read that variable using an SQL server proc, run a filter on lon/lat and insert it into the db. 
I am now considering using a console application to inject the data given the CLR limitations.

**Comment by IdahoSixString** [comment]
@SqlUser12 Using a console application to read the grib files and storing the data in a table would be your best bet and would cause the least headaches.

You can also write an extended stored procedure, which would call your console application (pass in a file name as args). However, these are a deprecated (no longer support, but you can still write them), which can read the file and pass back the data all in SQL.

Either way though I think the first option of just importing the data into a SQL table is by far the best solution and will cause you the least amount of problems.

**Comment by bnasko** [comment]
Thanks for the recommendation Idaho. In that case I will proceed with the console application route. I agree it will most likely be the cleanest solution.
Cheers!

**Comment by IdahoSixString** [comment]
@0x1mason We can close this ticket.

**Comment by 0x1mason** [comment]
This issue was moved to GribApiDotNet/GribApi.NET#7

**Comment by IdahoSixString** [comment]
This is only possible if the degrib process was written in a managed language. Otherwise there is no other way to load dll's into SQL clr.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 0x1mason** [comment]
@IdahoSixString I don't have any experience with SQL Server, but it sounds like at least some versions allow pinvoke. https://stackoverflow.com/questions/32290350/how-to-unload-native-dll-loaded-using-dllimport-attribute-from-sql-server
